steps:
  - name: 'google/cloud-sdk'
    args:
      [
        'gcloud',
        'beta',
        'functions',
        'deploy',
        'notify-rad-lab',
        '--gen2',
        '--runtime',
        'nodejs16',
        '--trigger-topic',
        'cloud-builds',
        '--entry-point',
        'notifyRadLab',
        '--source',
        '.',
        '--region',
        '${_REGION}',
        '--set-secrets',
        'SENDGRID_API_KEY=${_SENDGRID_API_KEY_SECRET_NAME}:latest',
        '--set-env-vars',
        'SENDGRID_SENDER_EMAIL=${_SENDGRID_SENDER_EMAIL}',
      ]
